build: 
	dotnet build ./qmux/qmux.csproj

test: 
	dotnet test ./qmux.tests/qmux.tests.csproj

clean_src: 
	dotnet clean ./qmux/qmux.csproj
clean_test: 
	dotnet clean ./qmux.tests/qmux.tests.csproj

clean: clean_src clean_test